MODEL:
  TYPE: swin_distill
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 100
  #BASE_LR: 5e-5 #1e-4
  WEIGHT_DECAY: 100
  BASE_LR: 100
  CLIP_GRAD: 5.0