MODEL:
  TYPE: swin_distill
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
TRAIN:
  #START_EPOCH: 3
  EPOCHS: 1
  BASE_LR: 5e-5 #1e-4
  #WEIGHT_DECAY: 10000000.0
  #BASE_LR: 1e-3